### ISSUE TITLE
Node version low and foundry init happens too late

### ISSUE THREAD

**Issue by villain4hire78** [grapeofwrath/foundryvtt-install-with-caddy-pm2#1]
Your node version is 14 and needs to be 18. 14 doesn't work.

You are trying to use PM2 before you initialize foundry. PM2 can't launch it until the user data structure is created.

I use timeout 10 node <foundry init string>

Also 30 seconds is too long. ADHD sucks.

Here is the version I used that worked on Ubuntu 22.10.
[foundry-install.txt](https://github.com/grapeofwrath/foundryvtt-install-with-caddy-pm2/files/10514815/foundry-install.txt)

**Comment by grapeofwrath** [comment]
I did a little more digging and switched the node version to 16. Node 18 should work fine, especially since I believe Foundry v11 will require that. However the wiki recommends v16.x at the moment. I definitely forgot that timeout existed lol.

see [commit 5a38a38](https://github.com/grapeofwrath/foundryvtt-install-with-caddy-pm2/commit/5a38a3858647f8d8abce1ccdf93764a3c969c2a8)
